server:
  port: 8006
spring:
  application:
    name: business
  cloud:
    nacos:
      discovery:
        server-addr: nacos.starbug.vip
        username: nacos
        password: starbug-docker-nacos
