server:
  port: 8005
spring:
  application:
    name: userpoints
  cloud:
    nacos:
      discovery:
        server-addr: nacos.starbug.vip
        username: nacos
        password: starbug-docker-nacos
