server:
  port: 8001
spring:
  application:
    name: placeorder
  cloud:
    nacos:
      discovery:
        server-addr: nacos.starbug.vip
        username: nacos
        password: starbug-docker-nacos
